apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ehpi-duckdns-cert
  namespace: app-dev
spec:
  secretName: ehpi-duckdns-tls
  issuerRef:
    name: letsencrypt-dev
    kind: ClusterIssuer
  commonName: ehpi.duckdns.org    # <<< change to your domain
  dnsNames:
  - ehpi.duckdns.org              # <<< change to your domain
