apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pi-ui-ingress
  namespace: app-dev
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dev
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
  - host: ehpi.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pi-ui
            port:
              number: 80
  tls:
  - hosts:
    - ehpi.duckdns.org
    secretName: duckdns-cert-tls
