apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pi-ui-dev-ingress
  namespace: app-dev
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dev
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: "nginx"
  tls:
  - hosts:
    - ehpi.duckdns.org
    secretName: ehpi-duckdns-tls
  rules:
  - host: ehpi.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pi-ui-dev
            port:
              number: 80
