apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-ui-prod
  namespace: app-prod
  labels:
    name: pi-ui-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pi-ui-prod
      name: pi-ui-prod
  template:
    metadata:
      labels:
        app: pi-ui-prod
        name: pi-ui-prod
    spec:
      containers:
        - name: pi-ui-prod
          image: erickhdez1997/pi-ui:prod
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: API_URL
              value: "http://backend.app-prod.svc.cluster.local:8080"