apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-ui
  namespace: app-staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pi-ui
  template:
    metadata:
      labels:
        app: pi-ui
    spec:
      containers:
        - name: pi-ui
          image: yourdockerhubusername/pi-ui:staging
          ports:
            - containerPort: 80
          env:
            - name: API_URL
              value: "http://backend.app-staging.svc.cluster.local:8080"
