apiVersion: v1
kind: Service
metadata:
  name: pi-ui-staging
  namespace: app-staging
  labels:
    name: pi-ui-staging
spec:
  selector:
    app: pi-ui-staging
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80