name: Build & Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU (for ARM builds)
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build & Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        platforms: linux/arm64,linux/amd64
        tags: erickhdez1997/pi-ui:dev
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

    - name: Deploy to Raspberry Pi (K3s)
      uses: appleboy/ssh-action@v0.1.10
      with:
        # host: ${{ secrets.DUCK_DNS_HOST }}
        host: ${{ secrets.IP_ADDRESS }}
        port: 22
        username: ${{ secrets.PI_USER }}
        key: ${{ secrets.PI_SSH_KEY }}
        script: |
          # Clone the repository on the Raspberry Pi
          export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
          cd /home/${{ secrets.PI_USER }}/kube-manifests
          git pull
          cd ~/kube-manifests/k8s/dev
          kubectl apply -f deployment.yaml -n app-dev
          kubectl apply -f service.yaml -n app-dev
          kubectl apply -f cluster-issuer.yaml -n app-dev
          kubectl apply -f certificate.yaml -n app-dev
          kubectl apply -f ingress.yaml -n app-dev
          kubectl rollout restart deployment pi-ui-dev -n app-dev
