name: Build & Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU (for ARM builds)
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build & Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        platforms: linux/arm64,linux/amd64
        tags: erickhdez1997/pi-ui:latest

    - name: Deploy to Raspberry Pi (K3s)
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.PI_IP }}
        port: 2222
        username: ${{ secrets.PI_USER }}
        key: ${{ secrets.PI_SSH_KEY }}
        script: |
          cd ~/your-kube-manifests
          git pull
          kubectl apply -f pi-ui-deployment.yaml -n app-dev
          kubectl rollout restart deployment pi-ui -n app-dev
