- name: Deploy to Raspberry Pi (K3s)
  uses: appleboy/ssh-action@v0.1.10
  with:
    host: ${{ secrets.PI_IP }}
    username: ${{ secrets.PI_USER }}
    key: ${{ secrets.PI_SSH_KEY }}
    script: |
      cd ~/your-kube-manifests
      git pull
      kubectl apply -f pi-ui-deployment.yaml -n app-dev
      kubectl rollout restart deployment pi-ui -n app-dev
